name:                generic-override-aeson
version:             0.0.0.3
github:              "estatico/generic-override"
license:             BSD3
author:              "Cary Robbins"
maintainer:          "carymrobbins@gmail.com"
copyright:           "2020 Estatico Studios LLC"
category:            Generics
description:         Please see the README on GitHub at <https://github.com/estatico/generic-override#readme>

synopsis:            Provides orphan instances necessary for integrating generic-override and aeson

extra-source-files:
  - README.md
  - CHANGELOG.md

dependencies:
- base >= 4.7 && < 5
- aeson >= 1.4 && < 2.1
- generic-override

library:
  source-dirs: src

tests:
  generic-override-aeson-test:
    main:                Test.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - generic-override-aeson
    - hspec
    - text
