# GENERATED HEADER START
name:                generic-override-aeson
version:             0.0.0.1
github:              "estatico/generic-override"
license:             BSD3
author:              "Cary Robbins"
maintainer:          "carymrobbins@gmail.com"
copyright:           "2020 Estatico Studios LLC"
category:            Generics
description:         Please see the README on GitHub at <https://github.com/estatico/generic-override#readme>
# GENERATED HEADER END

synopsis:            Provides orphan instances necessary for integrating generic-override and aeson

dependencies:
- base >= 4.7 && < 5
- aeson >= 1.4.5.0 && < 2
- generic-override

ghc-options:
- -Wall

library:
  source-dirs: src

tests:
  generic-override-aeson-test:
    main:                Test.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - generic-override-aeson
    - hspec
    - text
